package wsl.JLinkLabelLibrary;
/* JLinkLabelDevHarness.java
 * Created on March 3, 2007, 4:55 AM
 */

/*

 Copyright [2007] [Timothy Binkley-Jones]
 
 Licensed under the Apache License, Version 2.0 (the "License"); 
 you may not use this file except in compliance with the License. 
 You may obtain a copy of the License at 
    
    http://www.apache.org/licenses/LICENSE-2.0 
 
 Unless required by applicable law or agreed to in writing, software 
 distributed under the License is distributed on an "AS IS" BASIS, 
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 See the License for the specific language governing permissions and 
 limitations under the License. 

 */


import javax.swing.UIManager;

/** UI Development Harness.
 * @author  tim
 */
public class JLinkLabelDevHarness extends javax.swing.JFrame
{
    
    /** Creates new form JLinkLabelDevHarness. */
    public JLinkLabelDevHarness()
    {
	initComponents();
	setSize(1024,768);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLinkLabel1 = new JLinkLabel();
        jLinkLabel2 = new JLinkLabel();
        jLinkLabel3 = new JLinkLabel();
        jLinkLabel4 = new JLinkLabel();
        jPanel2 = new javax.swing.JPanel();
        jLinkLabel5 = new JLinkLabel();
        jLinkLabel8 = new JLinkLabel();
        jLinkLabel7 = new JLinkLabel();
        jLinkLabel6 = new JLinkLabel();
        jPanel3 = new javax.swing.JPanel();
        jLinkLabel9 = new JLinkLabel();
        jLinkLabel12 = new JLinkLabel();
        jLinkLabel11 = new JLinkLabel();
        jLinkLabel10 = new JLinkLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(2000, 2000));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 300));
        jLinkLabel1.setText("Once upon a time");
        jLinkLabel1.setActionCommand("http://one");
        jLinkLabel1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jLinkLabelActionPerformed(evt);
            }
        });

        jPanel1.add(jLinkLabel1);

        jLinkLabel2.setText("Once upon a time.");
        jLinkLabel2.setActionCommand("http://two");
        jLinkLabel2.setLength(4);
        jLinkLabel2.setStart(5);
        jLinkLabel2.setVisited(true);
        jLinkLabel2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jLinkLabelActionPerformed(evt);
            }
        });

        jPanel1.add(jLinkLabel2);

        jLinkLabel3.setText("Once upon a time.");
        jLinkLabel3.setActionCommand("http://three");
        jLinkLabel3.setLength(4);
        jLinkLabel3.setLinkColor(new java.awt.Color(153, 0, 0));
        jLinkLabel3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jLinkLabelActionPerformed(evt);
            }
        });

        jPanel1.add(jLinkLabel3);

        jLinkLabel4.setText("Once upon a time.");
        jLinkLabel4.setActionCommand("http://four");
        jLinkLabel4.setLength(4);
        jLinkLabel4.setLinkColor(new java.awt.Color(0, 102, 0));
        jLinkLabel4.setStart(12);
        jLinkLabel4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jLinkLabelActionPerformed(evt);
            }
        });

        jPanel1.add(jLinkLabel4);

        jPanel5.add(jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setMaximumSize(new java.awt.Dimension(2000, 2000));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 300));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 300));
        jLinkLabel5.setText("There once was king");
        jLinkLabel5.setActionCommand("http://five");
        jLinkLabel5.setLinkBehavior(1);
        jLinkLabel5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jLinkLabelActionPerformed(evt);
            }
        });

        jPanel2.add(jLinkLabel5);

        jLinkLabel8.setText("There once was king");
        jLinkLabel8.setActionCommand("http://six");
        jLinkLabel8.setLength(4);
        jLinkLabel8.setLinkBehavior(1);
        jLinkLabel8.setStart(5);
        jLinkLabel8.setVisited(true);
        jLinkLabel8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jLinkLabelActionPerformed(evt);
            }
        });

        jPanel2.add(jLinkLabel8);

        jLinkLabel7.setText("There once was king");
        jLinkLabel7.setActionCommand("http://seven");
        jLinkLabel7.setLength(4);
        jLinkLabel7.setLinkBehavior(1);
        jLinkLabel7.setLinkColor(new java.awt.Color(153, 0, 0));
        jLinkLabel7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jLinkLabelActionPerformed(evt);
            }
        });

        jPanel2.add(jLinkLabel7);

        jLinkLabel6.setText("There once was king");
        jLinkLabel6.setActionCommand("http://eight");
        jLinkLabel6.setLength(4);
        jLinkLabel6.setLinkBehavior(1);
        jLinkLabel6.setLinkColor(new java.awt.Color(0, 102, 0));
        jLinkLabel6.setStart(12);
        jLinkLabel6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jLinkLabelActionPerformed(evt);
            }
        });

        jPanel2.add(jLinkLabel6);

        jPanel5.add(jPanel2);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setMaximumSize(new java.awt.Dimension(2000, 2000));
        jPanel3.setMinimumSize(new java.awt.Dimension(100, 300));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 300));
        jLinkLabel9.setText("king went fishing");
        jLinkLabel9.setActionCommand("http://nine");
        jLinkLabel9.setLinkBehavior(2);
        jLinkLabel9.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jLinkLabelActionPerformed(evt);
            }
        });

        jPanel3.add(jLinkLabel9);

        jLinkLabel12.setText("king went fishing");
        jLinkLabel12.setActionCommand("http://ten");
        jLinkLabel12.setLength(4);
        jLinkLabel12.setLinkBehavior(2);
        jLinkLabel12.setStart(5);
        jLinkLabel12.setVisited(true);
        jLinkLabel12.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jLinkLabelActionPerformed(evt);
            }
        });

        jPanel3.add(jLinkLabel12);

        jLinkLabel11.setText("king went fishing");
        jLinkLabel11.setActionCommand("http://eleven");
        jLinkLabel11.setLength(4);
        jLinkLabel11.setLinkBehavior(2);
        jLinkLabel11.setLinkColor(new java.awt.Color(153, 0, 0));
        jLinkLabel11.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jLinkLabelActionPerformed(evt);
            }
        });

        jPanel3.add(jLinkLabel11);

        jLinkLabel10.setText("king went fishing");
        jLinkLabel10.setActionCommand("http://twelve");
        jLinkLabel10.setLength(4);
        jLinkLabel10.setLinkBehavior(2);
        jLinkLabel10.setLinkColor(new java.awt.Color(0, 102, 0));
        jLinkLabel10.setStart(12);
        jLinkLabel10.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jLinkLabelActionPerformed(evt);
            }
        });

        jPanel3.add(jLinkLabel10);

        jPanel5.add(jPanel3);

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Message:");
        jPanel6.add(jLabel1);

        jTextArea1.setColumns(50);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel6.add(jScrollPane1);

        jPanel4.add(jPanel6, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLinkLabelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jLinkLabelActionPerformed
    {//GEN-HEADEREND:event_jLinkLabelActionPerformed
	jTextArea1.append("ActionPerformed: " + evt.getActionCommand() + "\r\n");
    }//GEN-LAST:event_jLinkLabelActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
	try
	{
    	    System.setProperty("apple.laf.useScreenMenuBar","true");
	    System.setProperty("com.apple.mrj.application.apple.menu.about.name","Magnatis");
	    String lafName = UIManager.getSystemLookAndFeelClassName();
	    System.out.println("Default look and feel class: " + lafName);
//	    if( 0 == lafName.compareToIgnoreCase("javax.swing.plaf.metal.MetalLookAndFeel") ||
//		    0 == lafName.compareToIgnoreCase("com.sun.java.swing.plaf.gtk.GTKLookAndFeel") )
//	    {
//		//lafName = "com.jgoodies.looks.windows.WindowsLookAndFeel";
//		//lafName = "com.jgoodies.looks.plastic.PlasticLookAndFeel";
//		//lafName = "com.jgoodies.looks.plastic.Plastic3DLookAndFeel";
//		lafName = "com.jgoodies.looks.plastic.PlasticXPLookAndFeel";
//	    }
	    System.out.println("Attempting to use look and feel class: " + lafName);
	    UIManager.setLookAndFeel( lafName);
	    System.out.println("Using look and feel: " + UIManager.getLookAndFeel().getName());
	}
	catch (Exception e)
	{ 
	    System.out.println("Caught exception trying to set look and feel (" + e.toString() + ")");
	}
	java.awt.EventQueue.invokeLater(new Runnable()
	{
	    public void run()
	    {
		new JLinkLabelDevHarness().setVisible(true);
	    }
	});
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private JLinkLabel jLinkLabel1;
    private JLinkLabel jLinkLabel10;
    private JLinkLabel jLinkLabel11;
    private JLinkLabel jLinkLabel12;
    private JLinkLabel jLinkLabel2;
    private JLinkLabel jLinkLabel3;
    private JLinkLabel jLinkLabel4;
    private JLinkLabel jLinkLabel5;
    private JLinkLabel jLinkLabel6;
    private JLinkLabel jLinkLabel7;
    private JLinkLabel jLinkLabel8;
    private JLinkLabel jLinkLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
