pageinfo = [[1219888943,5535],
	[1219888883,7266],
	[1219892167,2516],
	[1208399281,6450],
	[1219955095,4460],
	[1219954077,15282],
	[1219977527,3951],
	[1219955125,5422],
	[1219888839,3589],
	[1219958319,12277],
	[1219958097,5931],
	[1219891871,3753],
	[1219958361,23178],
	[1224109521,12438],
	[1219889409,3892],
	[1219910839,7087]];
pagedata = [ ["./chapter_2.htm","Installation","﻿Installation Top 1 Previous Next 1 Download the software from www.mobiledatanow.com/product/download if you haven&#39;t already. Click on the install...",""],
["./creating_an_odbc_system_data_s.htm","Creating an ODBC System Data Source Name (DSN)","﻿Creating an ODBC System Data Source Name (DSN) Top 1 Previous Next 1 MobileDataNow comes supplied with the Microsoft Northwind sample database so...",""],
["./creating_a_new_project.htm","Creating a new Project","﻿Creating a new Project Top 1 Previous Next 1 By default, a sample project is already open when you first login to MobileDataNow, and for this pur...",""],
["./data_sources.htm","Data Sources","﻿Data Sources Top 1 Previous Next 1 Connect to a database To connect to a database, enter the details of the database connection in the New Connec...",""],
["./deployment.htm","Deployment","﻿Deployment Top 1 Previous Next 1 If you haven&#39;t already, start the relevant services as shown in Running MDN Services For the queries we&#39;ve creat...",""],
["./end_user_access.htm","Queries","﻿Queries Top 1 Previous Next 1 This section deals with setting up the queries to extract the data from the database for users and then deliver the...",""],
["./introduction.htm","Introduction","﻿Introduction Top Next 1 MobileDataNow lets you connect to databases and web services, then access that data using messaging (email, SMS text mess...",""],
["./mdn_server_settings.htm","Running MDN Services","﻿Running MDN Services Top 1 Previous Next 1 MobileDataNow runs services in the background to enable messaging functions to work and need to be sta...",""],
["./my_installations_screen.htm","My-installations screen","﻿My-installations screen Top 1 Previous Next 1 Note: You can skip this step if you want to just start using the application. This is related to ma...",""],
["./new_item.htm","Troubleshooting","﻿Troubleshooting Top 1 Previous 1. I&#39;m not getting any results back from my queries. Make sure you&#39;ve added your user to a Group and given that Gr...",""],
["./other_hints_and_tips.htm","Hints and tips","﻿Hints and tips Top 1 Previous Next 1 My MDN Account In the Settings screen, you can view your license details and change your registered email ad...",""],
["./overview_of_the_user_interface.htm","Overview of the user interface","﻿Overview of the user interface Top 1 Previous Next 1 After you login, a blank project tab will already be open. MobileDataNow uses a simple work ...",""],
["./second_topic.htm","Pre-installation guide","﻿Pre-installation guide Top 1 Previous Next 1 MobileDataNow is a java application which connects to databases via a JDBC or ODBC driver, then data...",""],
["./settings.htm","Messaging Settings","﻿Messaging Settings Top 1 Previous Next 1 One of the first things to do is to define some settings and add details for email, instant messaging an...",""],
["./sub_chapter_2_1.htm","Running the application","﻿Running the application Top 1 Previous Next 1 After installation of MobileDataNow, if you didn&#39;t start the windows services automatically you can...",""],
["./users__groups.htm","Users &#38; Groups","﻿Users &#38; Groups Top 1 Previous Next 1 Setup a Group Groups are used to define access privileges to data and can be setup for Named Users or for Pu...",""]];
